### ISSUE TITLE
Node version in package.json

### ISSUE THREAD

**Issue by vetrov** [stylelint-stylistic/stylelint-stylistic#5]
### What is the problem you're trying to solve?

Our project is still on node v14.

### What solution would you like to see?

The latest version of this plugin requires node version >= 18.16 ([link](https://github.com/firefoxic/stylelint-codeguide/blob/v0.3.2/package.json#L24)). 

Stylelint itself is fine with node >=14.13 ([link](https://github.com/stylelint/stylelint/blob/15.11.0/package.json#L224))

Is there any reason for higher version in this plugin? Should node version be at least the same version as stylelint?

**Comment by firefoxic** [comment]
Thanks for your question!
Yes, there is a reason for this restriction.

Let's start with the fact that now, before the release of `stylelint@16`, there is no particular need to use this plugin — it only duplicates some rules that are only marked as deprecated in `stylelint` itself for the time being. You can still use `stylelint` without the plugin by simply turning off annoying messages with the `--quiet-deprecation-warnings` flag.

The plugin will only become necessary with the release of `stylelint@16`, when [`node@14` will definitely be dropped](https://github.com/stylelint/stylelint/blob/v16/package.json#L222) (and maybe `node@16` too). As far as I know, the main reason for some developers to stay on `node@14` is to change their work with peer dependencies (maybe you have different reasons, it would be interesting to know about them). So if you accept this change and leave `node@14`, it's unlikely that anything will keep you on [`node@16`, which has been unmaintained for over a month now](https://nodejs.dev/en/about/releases/). In any case, when `stylelint@16` is released, you will have only two options:
- upgrade both `stylelint` (by adding this plugin) and `node.js`,
- or stay with `node@14` and leave `stylelint@15` with warnings disabled (without the plugin).

By the way, the stricter versioning requirements for peer dependencies turned out to be very important for the plugin. I have already faced a situation where an inconsistency between the plugin code and the code of the new `stylelint` version resulted in a non-functional linter. So now I'm trying to make the plugin compatible with new linter versions in time.
