### ISSUE TITLE
Add default config to export

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint-stylistic/stylelint-stylistic#9]
### What is the problem you're trying to solve?

Hello.

Thank you for porting these rules.

But I'd like to have some default configuration, with them enabled and configured properly.

They were in `stylelint-config-standard` before removing, as I know.

### What solution would you like to see?

Example: `stylelint-stylistic` (which doesn't support Stylelint v16 yet) has such option:

https://www.npmjs.com/package/stylelint-stylistic#usage

```json
{
  "extends": [
    "stylelint-stylistic/config"
  ]
}
```

https://github.com/elirasza/stylelint-stylistic/blob/main/config/index.js

**Comment by firefoxic** [comment]
Hi! Thank you! I think that's a good idea. But probably better in a separate repository. Firstly, to be consistent with Stylelint. And secondly, not to increase this package with things that not everyone will need.

Now we are preparing a renaming with a move to an organization. And in this organization it will be possible to add the config as a separate project.

What do you think?

**Comment by AlexWayfer** [comment]
> Hi! Thank you! I think that's a good idea. But probably better in a separate repository. Firstly, to be consistent with Stylelint. And secondly, not to increase this package with things that not everyone will need.
> 
> Now we are preparing a renaming with a move to an organization. And in this organization it will be possible to add the config as a separate project.
> 
> What do you think?

As you wish.

It has pros, which you've highlighted. But it also has cons, for example, when you modifying rules, add news, drop some. I mean, there will be required some kind of version locks.

I, honestly, see no oversize problems with simple 100 lines single file, which is optional and easy to use "out of box".

But it's your project, and it's up to you.

**Comment by XhmikosR** [comment]
IMHO the config should be in this repo. It's common practice. And while at it, it'd be awesome if you just enabled by default the rules that https://github.com/elirasza/stylelint-stylistic had to make the switch easier for everyone :)

**Comment by hooray** [comment]
Continuously following

**Comment by firefoxic** [comment]
First I would like to thank you for your patience. But before making any decision, I had to research this topic. And here's what I discovered:

1. Built-in config is too non-obvious a plugin feature. For example, in [this PR](https://github.com/stylelint/awesome-stylelint/pull/63) I had to click through all the links to plugins. Along the way, I tried to find some that have built-in configs. I may have missed some just because of the non-obviousness of this approach. Not all users read README beyond the line with the package installation.
2. On the contrary, a separate package, besides the same mention in the README of the plugin, can get at least in [`awesome-stylelint`](https://github.com/stylelint/awesome-stylelint#configs) and maybe somewhere else. This will make it known to a wider range of users.
3. Plugins that have a built-in config are the exception rather than the rule. One such plugin is `stylelint-a11y`. Its config contains only 3 highly recommended rules, which are important for accessibility (at least according to the author of the plugin). The second one I can't even remember now, and I haven't met anymore (I may have missed it, which brings us back to point 1).
4. `@stylistic/stylelint-plugin` is not about syntax, but about code styling. And everyone may have his own opinion on this matter. And any variant, even copied directly from the deleted lines in `stylelint-config-standard`, will be overconfident for many people. @XhmikosR Even you [override 16 rules in your config, 4 of which you simply disable](https://github.com/twbs/stylelint-config-twbs-bootstrap/pull/236/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346). Someone may have that number more than half of the entire built-in config, in which case it will be more of a hindrance than a help.
5. In addition, a separate config package will eliminate the need to plug in the plugin itself. It is enough to add `@stylistic/stylelint-config-standard` to the already existing `stylelint-config-standard` and then expand your config in the usual way.
6. I'd like to cover the config with tests, and there are already a huge number of tests in this plugin package. Embedding the config in the plugin will only complicate support and, as a consequence, slow down updates.

Of the positives for embedding the config, the only one I can see is that there is no additional dependency. But point 5 not only equalizes this advantage, but even looks like a more attractive option.

From the above, I conclude that it would be better to make this config in a separate package. I'm just not sure about the name: whether the word `standard` should be left in it (so far I'm inclined to think that it will be unnecessary).

@elirasza Any thoughts on the above? Especially considering that you have embedded the config inside your plugin.

**Comment by elirasza** [comment]
I do agree with you that with a single-responsibility mindset, each package should have its own responsibility: one defining rules, the other proposing an implementation of said rules.

That being said, when I carried the old stylistic rules in my package, the choice of bundling the config in the package was user-oriented. I noticed many people were inconvenienced by this loss, and found a one package solution to be the easiest answer to this. The bundled config only implements rules from this package, as `stylelint-a11y` aldo does, so it only gives an optional, quick and override-able solution.

I personally prefer packages which offer minimal post-install configuration. If this package were to be split as you would like to, which I am not against, the user should absolutely be aware they have to add another dependency or implement all rules by themselves. If as you said, not all of them have a thorough read of the README.md, wouldn't it be a bit tedious ?

**Comment by firefoxic** [comment]
> the user should absolutely be aware they have to add another dependency or implement all rules by themselves.

For comparison:
1. Case with built-in config

   _package.json_
   ```json
   {
   	"devDependencies": {
   		"@stylistic/stylelint-plugin": "^2.0.0",
   		"stylelint": "^16.0.2",
   		"stylelint-config-standard": "35.0.0"
   	}
   }
   ```
   _.stylelintrc_
   ```json
   {
   	"extends": [
   		"stylelint-config-standard",
   		"@stylistic/stylelint-plugin/config"
   	],
   	"plugins": [
   		"@stylistic/stylelint-plugin"
   	],
   	"rules": {
   		"@stylistic/indentation": "tab"
   	}
   }
   ```

2. Case with a separate config package

   _package.json_
   ```json
   {
   	"devDependencies": {
   		"@stylistic/stylelint-config": "^1.0.0",
   		"stylelint": "^16.0.2",
   		"stylelint-config-standard": "35.0.0"
   	}
   }
   ```
   _.stylelintrc_
   ```json
   {
   	"extends": [
   		"stylelint-config-standard",
   		"@stylistic/stylelint-config"
   	],
   	"rules": {
   		"@stylistic/indentation": "tab"
   	}
   }
   ```

IMO, the second case looks even easier for end users — they don't have to specify a plugin, whereas the config has to be specified anyway.

---
We could go even further and extend this config with the standard config. But then there will be a collision between the package name and its contents: `@stylistic/stylelint-config` contains the whole set of syntax rules from the standard and recommended configs. This is too much.

**Comment by hooray** [comment]
For me, I don't care about which configuration method to use. I just hope to continue using the removed 76 rules, even if it's providing a complete configuration reference in README.

For example, this is how I use it now: 

```js
export default {
  plugins: [
    '@stylistic/stylelint-plugin',
  ],
  rules: {
    // refer to https://github.com/elirasza/stylelint-stylistic/blob/main/config/index.js
    '@stylistic/at-rule-name-case': 'lower',
    '@stylistic/at-rule-name-space-after': 'always-single-line',
    '@stylistic/at-rule-semicolon-newline-after': 'always',
    '@stylistic/block-closing-brace-empty-line-before': 'never',
    '@stylistic/block-closing-brace-newline-after': 'always',
    '@stylistic/block-closing-brace-newline-before': 'always-multi-line',
    '@stylistic/block-closing-brace-space-before': 'always-single-line',
    '@stylistic/block-opening-brace-newline-after': 'always-multi-line',
    '@stylistic/block-opening-brace-space-after': 'always-single-line',
    '@stylistic/block-opening-brace-space-before': 'always',
    '@stylistic/color-hex-case': 'lower',
    '@stylistic/declaration-bang-space-after': 'never',
    '@stylistic/declaration-bang-space-before': 'always',
    '@stylistic/declaration-block-semicolon-newline-after': 'always-multi-line',
    '@stylistic/declaration-block-semicolon-space-after': 'always-single-line',
    '@stylistic/declaration-block-semicolon-space-before': 'never',
    '@stylistic/declaration-block-trailing-semicolon': 'always',
    '@stylistic/declaration-colon-newline-after': 'always-multi-line',
    '@stylistic/declaration-colon-space-after': 'always-single-line',
    '@stylistic/declaration-colon-space-before': 'never',
    '@stylistic/function-comma-newline-after': 'always-multi-line',
    '@stylistic/function-comma-space-after': 'always-single-line',
    '@stylistic/function-comma-space-before': 'never',
    '@stylistic/function-max-empty-lines': 0,
    '@stylistic/function-parentheses-newline-inside': 'always-multi-line',
    '@stylistic/function-parentheses-space-inside': 'never-single-line',
    '@stylistic/function-whitespace-after': 'always',
    '@stylistic/indentation': 2,
    '@stylistic/max-empty-lines': 1,
    '@stylistic/max-line-length': 120,
    '@stylistic/media-feature-colon-space-after': 'always',
    '@stylistic/media-feature-colon-space-before': 'never',
    '@stylistic/media-feature-name-case': 'lower',
    '@stylistic/media-feature-parentheses-space-inside': 'never',
    '@stylistic/media-feature-range-operator-space-after': 'always',
    '@stylistic/media-feature-range-operator-space-before': 'always',
    '@stylistic/media-query-list-comma-newline-after': 'always-multi-line',
    '@stylistic/media-query-list-comma-space-after': 'always-single-line',
    '@stylistic/media-query-list-comma-space-before': 'never',
    '@stylistic/no-empty-first-line': true,
    '@stylistic/no-eol-whitespace': true,
    '@stylistic/no-extra-semicolons': true,
    '@stylistic/no-missing-end-of-source-newline': true,
    '@stylistic/number-leading-zero': 'always',
    '@stylistic/number-no-trailing-zeros': true,
    '@stylistic/property-case': 'lower',
    '@stylistic/selector-attribute-brackets-space-inside': 'never',
    '@stylistic/selector-attribute-operator-space-after': 'never',
    '@stylistic/selector-attribute-operator-space-before': 'never',
    '@stylistic/selector-combinator-space-after': 'always',
    '@stylistic/selector-combinator-space-before': 'always',
    '@stylistic/selector-descendant-combinator-no-non-space': true,
    '@stylistic/selector-list-comma-newline-after': 'always',
    '@stylistic/selector-list-comma-space-before': 'never',
    '@stylistic/selector-max-empty-lines': 0,
    '@stylistic/selector-pseudo-class-case': 'lower',
    '@stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
    '@stylistic/selector-pseudo-element-case': 'lower',
    '@stylistic/string-quotes': 'double',
    '@stylistic/unit-case': 'lower',
    '@stylistic/value-list-comma-newline-after': 'always-multi-line',
    '@stylistic/value-list-comma-space-after': 'always-single-line',
    '@stylistic/value-list-comma-space-before': 'never',
    '@stylistic/value-list-max-empty-lines': 0,
  },
}
```

**Comment by firefoxic** [comment]
Thank you all for your patience!

The config is ready to use: https://www.npmjs.com/package/@stylistic/stylelint-config 🚀
